### ISSUE TITLE
Admin panel is yielding an error on Access

### ISSUE THREAD

**Issue by EffeArts** [ndasilver/food_delivery#44]
Below is the error message:

" **Facade\Ignition\Exceptions\ViewException
Trying to get property 'name' of non-object (View: C:\xampp\htdocs\food_delivery\resources\views\Admin\dash.blade.php)** "

I think it has something to do with relationships between order_items and menus tables, considering the error message below: 

**[ Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\xampp\htdocs\food_delivery\resources\views/Admin/dash.blade.php:112 ]**

**Comment by ndasilver** [comment]
Is it possible to attach screenshot?

**Comment by ndasilver** [comment]
Can you also review the last PR? I think it might be because I changed something in the migration, I didn't want to migrate again

**Comment by EffeArts** [comment]
It's all good now. Kudos
